--drop table [dbo].[AccountUsers]
--drop table [dbo].[AccountAddresses]
--drop table [dbo].[Addresses]
--drop table [dbo].[Users]
--drop table [dbo].[Accounts]
--drop table [dbo].[CommonMasterDetails]
--drop table [dbo].[CommonMasterHeaders]
--drop table [dbo].[__EFMigrationsHistory]

select * from  [dbo].[AccountUsers]
select * from  [dbo].[AccountAddresses]
select * from  [dbo].[Addresses]
select * from  [dbo].[Users]
select * from  [dbo].[Accounts]
select * from  [dbo].[CommonMasterDetails]
select * from  [dbo].[CommonMasterHeaders]